/* ============================================
   أرشيف عبدالحليم حافظ — قاعدة البيانات
   البيانات مجمعة من مصادر موثوقة متعددة
   ============================================ */

const ARCHIVE_DATA = {

  /* ===== الملحنون ===== */
  composers: [
    { id: "c-mohamed-mougi", name: "محمد الموجي", bio: "موسيقار مصري من أبرز ملحني الأغنية العربية الحديثة، تعاون بشكل مكثف مع عبدالحليم حافظ." },
    { id: "c-kamal-el-tawil", name: "كمال الطويل", bio: "موسيقار مصري وزميل عبدالحليم في معهد الموسيقى العربية، من أهم ملحني الأغنية الوطنية والعاطفية." },
    { id: "c-balegh-hamdi", name: "بليغ حمدي", bio: "موسيقار مصري لقب بـ«موسيقار الأجيال»، شكل مع عبدالحليم والشاعر محمد حمزة ثلاثيًا فنيًا قدم أبرز أغاني السبعينيات." },
    { id: "c-mohamed-abdelwahab", name: "محمد عبد الوهاب", bio: "موسيقار الأجيال، أحد أعظم ملحني الموسيقى العربية في القرن العشرين." },
    { id: "c-mounir-murad", name: "منير مراد", bio: "ملحن مصري قدم ألحانًا خفيفة ومميزة، شارك في تلحين عدة أغانٍ لعبدالحليم." },
    { id: "c-hussein-geneid", name: "حسين جنيد", bio: "ملحن مصري من أوائل من تعاون مع عبدالحليم في بداياته." },
    { id: "c-abdelhamid-zaki", name: "عبد الحميد توفيق زكي", bio: "ملحن مصري أسس فرقة الأنغام الذهبية بالإذاعة المصرية، لحن لأغاني عبدالحليم الأولى." },
    { id: "c-ali-ismail", name: "علي إسماعيل", bio: "ملحن مصري وموزع موسيقي تعاون مع عبدالحليم في فترات مبكرة." },
    { id: "c-riyad-sunbati", name: "رياض السنباطي", bio: "موسيقار مصري كبير، من أعظم ملحني القرن العشرين في الموسيقى العربية." },
    { id: "c-mahmoud-el-sharif", name: "محمود الشريف", bio: "ملحن مصري قدم ألحانًا شعبية مميزة." },
    { id: "c-ahmed-sabri", name: "أحمد صبرة", bio: "ملحن مصري." },
    { id: "c-ahmed-sedqi", name: "أحمد صدقي", bio: "ملحن مصري." },
    { id: "c-youssef-shawqi", name: "د. يوسف شوقي", bio: "ملحن مصري." },
    { id: "c-abdelhalim-ali", name: "عبد الحليم علي", bio: "ملحن مصري." },
    { id: "c-fouad-helmi", name: "فؤاد حلمي", bio: "ملحن مصري." },
    { id: "c-khalil-el-masri", name: "خليل المصري", bio: "ملحن مصري." },
    { id: "c-abdelhalim-nweira", name: "عبد الحليم نويرة", bio: "ملحن مصري." },
    { id: "c-raouf-zahni", name: "رؤوف ذهني", bio: "ملحن مصري." },
    { id: "c-ali-farag", name: "علي فراج", bio: "ملحن مصري." },
    { id: "c-mahmoud-kamel", name: "محمود كامل", bio: "ملحن مصري." },
    { id: "c-saud-el-rashid", name: "سعود الراشد", bio: "ملحن." },
    { id: "c-abdelazim-mohamed", name: "عبد العظيم محمد", bio: "ملحن مصري." },
    { id: "c-ibrahim-rajab", name: "إبراهيم رجب", bio: "ملحن مصري." },
    { id: "c-helmi-bakr", name: "حلمي بكر", bio: "ملحن مصري." },
    { id: "c-abdelhamid-el-sayed", name: "عبد الحميد السيد", bio: "ملحن مصري." },
    { id: "c-hamad-el-rajib", name: "حمد الرجيب", bio: "ملحن." },
    { id: "c-rahbani-brothers", name: "الأخوين رحباني", bio: "الأخوان عاصي ومنصور الرحباني، ملحنان لبنانيان شهيران." },
  ],

  /* ===== الشعراء ===== */
  lyricists: [
    { id: "l-mohamed-hamza", name: "محمد حمزة", bio: "شاعر مصري شكل مع عبدالحليم وبليغ حمدي ثلاثيًا قدم أبرز أغاني السبعينيات." },
    { id: "l-mursi-gamil-aziz", name: "مرسي جميل عزيز", bio: "شاعر مصري من أبرز شعراء الأغنية العربية." },
    { id: "l-mamoun-shinawi", name: "مأمون الشناوي", bio: "شاعر مصري من أهم شعراء الأغنية العربية." },
    { id: "l-hussein-el-sayed", name: "حسين السيد", bio: "شاعر مصري غنائي كبير." },
    { id: "l-abdelrahman-el-abinoudi", name: "عبد الرحمن الأبنودي", bio: "شاعر مصري من أهم شعراء العامية والغناء الوطني." },
    { id: "l-salah-jahin", name: "صلاح جاهين", bio: "شاعر وفنان مصري شامل، من رواد الأغنية الوطنية." },
    { id: "l-nizar-qabbani", name: "نزار قباني", bio: "شاعر ودبلوماسي سوري، من أشهر شعراء العربية في القرن العشرين." },
    { id: "l-mohamed-ali-ahmed", name: "محمد علي أحمد", bio: "شاعر مصري غنائي." },
    { id: "l-abdel-fattah-mustafa", name: "عبد الفتاح مصطفى", bio: "شاعر مصري." },
    { id: "l-ismail-el-habrouk", name: "إسماعيل الحبروك", bio: "شاعر مصري." },
    { id: "l-fathi-qora", name: "فتحي قورة", bio: "شاعر مصري." },
    { id: "l-samir-mahjoub", name: "سمير محبوب", bio: "شاعر مصري." },
    { id: "l-kamel-el-shinawi", name: "كامل الشناوي", bio: "شاعر مصري كبير." },
    { id: "l-ahmed-shafik-kamel", name: "أحمد شفيق كامل", bio: "شاعر مصري." },
    { id: "l-salah-abdul-sabour", name: "صلاح عبد الصبور", bio: "شاعر مصري معاصر." },
    { id: "l-imam-el-saftawi", name: "إمام الصفطاوي", bio: "شاعر مصري." },
    { id: "l-abdelrahman-el-khamisi", name: "عبد الرحمن الخميسي", bio: "شاعر مصري." },
    { id: "l-ahmed-makhimar", name: "أحمد مخيمر", bio: "شاعر مصري." },
    { id: "l-mustafa-abdelrahman", name: "مصطفى عبد الرحمن", bio: "شاعر مصري." },
    { id: "l-zain-el-abidin", name: "زين العابدين عبد الله", bio: "شاعر." },
    { id: "l-ahmed-helmi", name: "أحمد حلمي", bio: "شاعر مصري." },
    { id: "l-abdelmoneim-el-sabaa", name: "عبد المنعم السباعي", bio: "شاعر مصري." },
    { id: "l-abdullah-el-faisal", name: "عبد الله الفيصل", bio: "أمير وشاعر سعودي." },
    { id: "l-saleh-joudat", name: "صالح جودت", bio: "شاعر مصري." },
    { id: "l-ahmed-el-samra", name: "أحمد السمرة", bio: "شاعر مصري." },
    { id: "l-mahmoud-hassan-ismail", name: "محمود حسن إسماعيل", bio: "شاعر مصري." },
    { id: "l-ali-mahdi", name: "علي مهدي", bio: "شاعر." },
    { id: "l-youssef-izzedin", name: "يوسف عز الدين عيسى", bio: "شاعر مصري." },
    { id: "l-abdel-fattah-asal", name: "عبد الفتاح عسل", bio: "شاعر." },
    { id: "l-mohamed-halawa", name: "محمد حلاوة", bio: "شاعر مصري." },
    { id: "l-ibrahim-mohamed-naja", name: "إبراهيم محمد نجا", bio: "شاعر مصري." },
    { id: "l-ahmed-shafik-kamel2", name: "أحمد شفيق كامل", bio: "شاعر مصري." },
    { id: "l-mohsen-el-khayat", name: "محسن الخياط", bio: "شاعر مصري." },
    { id: "l-abdelrahim-mansour", name: "عبد الرحيم منصور", bio: "شاعر مصري." },
    { id: "l-kamel-mansour", name: "كمال منصور", bio: "شاعر." },
    { id: "l-mohamed-salman", name: "محمد سلمان", bio: "شاعر." },
    { id: "l-abdulmohsen-el-refai", name: "عبد المحسن الرفاعي", bio: "شاعر." },
    { id: "l-abdelmajid-bin-jeddo", name: "عبد المجيد بن جدو", bio: "شاعر." },
    { id: "l-walid-jaafar", name: "وليد جعفر", bio: "شاعر." },
    { id: "l-ahmed-el-adwani", name: "أحمد العدواني", bio: "شاعر." },
    { id: "l-khaled-bin-saud", name: "خالد بن سعود", bio: "شاعر." },
    { id: "l-abdelwahab-mohamed", name: "عبد الوهاب محمد", bio: "شاعر مصري." },
    { id: "l-mustafa-el-damrani", name: "مصطفى الضمراني", bio: "شاعر." },
    { id: "l-mahmoud-abdelhay", name: "محمود عبد الحي", bio: "شاعر." },
    { id: "l-salah-abu-salem", name: "صلاح أبو سالم", bio: "شاعر." },
    { id: "l-anwar-abdullah", name: "أنور عبد الله", bio: "شاعر." },
    { id: "l-mohamed-el-halwani", name: "محمد الحلواني", bio: "شاعر." },
    { id: "l-najah-abdelhamid", name: "نجاح عبد الحميد", bio: "شاعر." },
    { id: "l-magdy-naguib", name: "مجدي نجيب", bio: "شاعر." },
    { id: "l-ibrahim-kamel-refaat", name: "إبراهيم كامل رفعت", bio: "شاعر." },
    { id: "l-fathi-qora2", name: "فتحي قورة", bio: "شاعر مصري." },
    { id: "l-hassan-mohamed-haha", name: "حسن محمد حاحا", bio: "شاعر." },
  ],

  /* ===== التصنيفات ===== */
  categories: [
    { id: "cat-film", name: "أغاني الأفلام" },
    { id: "cat-concert", name: "أغاني الحفلات" },
    { id: "cat-rare", name: "التسجيلات النادرة" },
    { id: "cat-radio", name: "التسجيلات الإذاعية" },
    { id: "cat-studio", name: "تسجيلات الاستوديو" },
    { id: "cat-live", name: "تسجيلات حية" },
    { id: "cat-national", name: "أغاني وطنية" },
    { id: "cat-romantic", name: "أغاني عاطفية" },
    { id: "cat-religious", name: "أغاني دينية" },
    { id: "cat-other", name: "أغاني أخرى" },
  ],

  /* ===== الأفلام ===== */
  films: [
    { id: "f-lahn-el-wafaa", title: "لحن الوفاء", year: 1955, poster: "", description: "أول فيلم سينمائي لعبدالحليم حافظ، شاركته البطولة شادية.", coStars: "شادية، حسين رياض", director: "إبراهيم عمارة" },
    { id: "f-ayyamna-el-helwa", title: "أيامنا الحلوة", year: 1955, poster: "", description: "شاركه البطولة فاتن حمامة وعمر الشريف وأحمد رمزي.", coStars: "فاتن حمامة، عمر الشريف، أحمد رمزي", director: "" },
    { id: "f-layali-el-hob", title: "ليالي الحب", year: 1955, poster: "", description: "", coStars: "آمال فريد، عبد السلام النابلسي", director: "" },
    { id: "f-ayyam-wa-layali", title: "أيام وليالي", year: 1955, poster: "", description: "", coStars: "إيمان، أحمد رمزي، محمود المليجي", director: "" },
    { id: "f-mawad-gharam", title: "موعد غرام", year: 1956, poster: "", description: "", coStars: "فاتن حمامة، عماد حمدي، زهرة العلا، رشدي أباظة", director: "" },
    { id: "f-dalila", title: "دليلة", year: 1956, poster: "", description: "أول فيلم مصري ملون بطريقة السكوب.", coStars: "شادية، فردوس محمد", director: "" },
    { id: "f-banat-el-yom", title: "بنات اليوم", year: 1957, poster: "", description: "", coStars: "ماجدة، آمال فريد، أحمد رمزي", director: "" },
    { id: "f-el-wisada-el-khaliya", title: "الوسادة الخالية", year: 1957, poster: "", description: "منقول عن رواية للأديب المصري إحسان عبد القدوس.", coStars: "أحمد رمزي، زهرة العلا، لبنى عبد العزيز، عمر الحريري", director: "" },
    { id: "f-fata-ahlami", title: "فتى أحلامي", year: 1957, poster: "", description: "", coStars: "آمال فريد، عبد السلام النابلسي", director: "" },
    { id: "f-share3-el-hob", title: "شارع الحب", year: 1958, poster: "", description: "", coStars: "صباح، عبد السلام النابلسي، حسين رياض", director: "" },
    { id: "f-hekayet-hob", title: "حكاية حب", year: 1959, poster: "", description: "", coStars: "مريم فخر الدين، عبد السلام النابلسي، محمود المليجي", director: "" },
    { id: "f-el-banat-wel-sayf", title: "البنات والصيف", year: 1960, poster: "", description: "", coStars: "سعاد حسني", director: "" },
    { id: "f-yawm-min-omri", title: "يوم من عمري", year: 1961, poster: "", description: "", coStars: "زبيدة ثروت، عبد السلام النابلسي، محمود المليجي، سهير البابلي", director: "" },
    { id: "f-el-khataya", title: "الخطايا", year: 1962, poster: "", description: "", coStars: "عماد حمدي، حسن يوسف، نادية لطفي، مديحة يسري", director: "" },
    { id: "f-maboudat-el-gamahir", title: "معبودة الجماهير", year: 1967, poster: "", description: "", coStars: "شادية، فؤاد المهندس، يوسف شعبان", director: "" },
    { id: "f-abi-fawq-el-shagara", title: "أبي فوق الشجرة", year: 1969, poster: "", description: "آخر فيلم سينمائي لعبدالحليم حافظ.", coStars: "عماد حمدي، ميرفت أمين، نادية لطفي", director: "" },
  ],

  /* ===== الحفلات ===== */
  concerts: [
    { id: "concert-albert-hall", title: "حفلة قاعة ألبرت هول — لندن", city: "لندن", country: "إنجلترا", year: 1967, date: "1967", venue: "قاعة ألبرت هول", description: "حفلة تاريخية بعد حرب 1967 أمام 8 آلاف شخص لصالح المجهود الحربي وإزالة آثار العدوان. قدم فيها أغنيتي «المسيح» و«عدى النهار».", songs: [] },
    { id: "concert-paris", title: "حفلة باريس", city: "باريس", country: "فرنسا", year: 1974, date: "أكتوبر 1974", venue: "قاعة باليه دي كونجريه", description: "حفلة في باريس حضرها حوالي 7000 مشاهد بين عرب وأجانب، وغنى فيها عبدالحليم أمام جمهور كبير.", songs: [] },
    { id: "concert-beirut", title: "حفلة بيروت", city: "بيروت", country: "لبنان", year: 1970, date: "1970", venue: "", description: "غنى عبدالحليم لجنوب لبنان في حفلة بيروت عقب معارك العرقوب.", songs: [] },
    { id: "concert-awlad-el-nile", title: "حفلة أضواء المدينة — حديقة الأندلس", city: "القاهرة", country: "مصر", year: 1953, date: "18 يونيو 1953", venue: "حديقة الأندلس", description: "حفلته الرسمية الأولى، وكانت أيضًا أول احتفال رسمي بإعلان الجمهورية.", songs: [] },
    { id: "concert-aswan", title: "حفلة السد العالي — أسوان", city: "أسوان", country: "مصر", year: 1960, date: "1960", venue: "أسوان", description: "حفلة أضواء المدينة للاحتفال بوضع حجر الأساس لبناء السد العالي، قدم فيها أغنية «حكاية شعب».", songs: [] },
  ],

  /* ===== الأغاني ===== */
  songs: [
    // ---- الخمسينيات 1951-1959 ----
    { id: "s-001", title: "الأصيل", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-002", title: "الأصيل الذهبي", year: null, decade: 1950, composerId: "c-abdelhamid-zaki", lyricistId: "l-abdelrahman-el-khamisi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-003", title: "احتار خيالي", year: null, decade: 1950, composerId: "c-hussein-geneid", lyricistId: "l-mohamed-ali-ahmed", filmId: "f-lahn-el-wafaa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع شادية", sources: ["wikipedia-ar"] },
    { id: "s-004", title: "إحنا الشعب", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-005", title: "إحنا كنا فين", year: null, decade: 1950, composerId: "c-mounir-murad", lyricistId: "l-hussein-el-sayed", filmId: "f-dalila", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع شادية", sources: ["wikipedia-ar"] },
    { id: "s-006", title: "أحن إليك", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-ali-ahmed", filmId: "f-lahn-el-wafaa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-007", title: "اسبقني يا قلبي", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-008", title: "اصحى وقوم", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-009", title: "أقبل الصباح", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-ahmed-makhimar", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "برنامج فتاة النيل", sources: ["wikipedia-ar"] },
    { id: "s-010", title: "أقول ما أقولشي", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mamoun-shinawi", filmId: "f-layali-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-011", title: "أنا أهواك", year: null, decade: 1950, composerId: "c-hussein-geneid", lyricistId: "l-fathi-qora", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع برلنتي حسن في فيلم بائعة الخبز", sources: ["wikipedia-ar"] },
    { id: "s-012", title: "أنا لك على طول", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mamoun-shinawi", filmId: "f-ayyam-wa-layali", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-013", title: "إنت إلهام جديد", year: null, decade: 1950, composerId: "c-youssef-shawqi", lyricistId: "l-mustafa-abdelrahman", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-014", title: "إنت غريب", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غنتها مديحة عبد الحليم", sources: ["wikipedia-ar"] },
    { id: "s-015", title: "إني ملكت في يدي زمامي", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-016", title: "أهل الهنا", year: null, decade: 1950, composerId: "c-abdelhalim-ali", lyricistId: "l-ibrahim-rajab", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "برنامج معروف الإسكافي", sources: ["wikipedia-ar"] },
    { id: "s-017", title: "أهواك", year: 1957, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-banat-el-yom", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar", "marefa"] },
    { id: "s-018", title: "أول مرة تحب يا قلبي", year: null, decade: 1950, composerId: "c-mounir-murad", lyricistId: "l-ismail-el-habrouk", filmId: "f-el-wisada-el-khaliya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-019", title: "إيه ذنبي إيه", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mamoun-shinawi", filmId: "f-ayyam-wa-layali", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-020", title: "إيه فكرك", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-021", title: "بتلوموني ليه", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-hekayet-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-022", title: "بحلم بيك", year: null, decade: 1950, composerId: "c-mounir-murad", lyricistId: "l-mursi-gamil-aziz", filmId: "f-hekayet-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-023", title: "بدلتي الزرقاء", year: null, decade: 1950, composerId: "c-abdelhamid-zaki", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-024", title: "بكرة وبعده", year: null, decade: 1950, composerId: "c-mounir-murad", lyricistId: "l-fathi-qora", filmId: "f-fata-ahlami", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-025", title: "البلبل والزهرة", year: null, decade: 1950, composerId: "c-youssef-shawqi", lyricistId: "l-zain-el-abidin", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع عصمت عبد العليم", sources: ["wikipedia-ar"] },
    { id: "s-026", title: "بيع قلبك", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-hussein-el-sayed", filmId: "f-fata-ahlami", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-027", title: "بيني وبين قلبي", year: null, decade: 1950, composerId: "c-khalil-el-masri", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-028", title: "بيني وبينك إيه", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-mawad-gharam", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-029", title: "تخونوه", year: null, decade: 1950, composerId: "c-balegh-hamdi", lyricistId: "l-ismail-el-habrouk", filmId: "f-el-wisada-el-khaliya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-030", title: "تعالي أقولك", year: null, decade: 1950, composerId: "c-mounir-murad", lyricistId: "l-fathi-qora", filmId: "f-lahn-el-wafaa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع شادية", sources: ["wikipedia-ar"] },
    { id: "s-031", title: "توبة", year: 1955, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-ayyam-wa-layali", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أول أغنية يلحنها محمد عبد الوهاب لعبدالحليم", sources: ["wikipedia-ar", "marefa"] },
    { id: "s-032", title: "ثورتنا المصرية", year: null, decade: 1950, composerId: "c-raouf-zahni", lyricistId: "l-mamoun-shinawi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-033", title: "جانا الخير", year: null, decade: 1950, composerId: "c-ahmed-sedqi", lyricistId: "l-najah-abdelhamid", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-034", title: "الجدول", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-035", title: "الجمال هو", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-036", title: "حبك نار", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: "f-hekayet-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-037", title: "حبيب حياتي", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-hussein-el-sayed", filmId: "f-dalila", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-038", title: "حبيبي في عنيّه", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-ibrahim-rajab", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-039", title: "حرام يا نار", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-hussein-el-sayed", filmId: "f-dalila", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-040", title: "الحق عليه", year: null, decade: 1950, composerId: "c-mounir-murad", lyricistId: "l-hussein-el-sayed", filmId: "f-dalila", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-041", title: "حلفني", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-layali-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-042", title: "الحق عليّا اللي عرفتك", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-043", title: "الحلو حياتي", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-ayyamna-el-helwa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-044", title: "حلو وكداب", year: null, decade: 1950, composerId: "c-mahmoud-el-sharif", lyricistId: "l-mamoun-shinawi", filmId: "f-mawad-gharam", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-045", title: "خسارة.. خسارة", year: null, decade: 1950, composerId: "c-balegh-hamdi", lyricistId: "l-mamoun-shinawi", filmId: "f-fata-ahlami", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-046", title: "خليك معايا", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-abdelmoneim-el-sabaa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-047", title: "الدنيا كلها (أنشودة الحياة)", year: null, decade: 1950, composerId: "c-abdelhamid-zaki", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-048", title: "ذات ليلة", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-049", title: "ذاك عيد الندى", year: null, decade: 1950, composerId: "c-hussein-geneid", lyricistId: "l-mustafa-abdelrahman", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-050", title: "ربما", year: null, decade: 1950, composerId: "c-mahmoud-kamel", lyricistId: "l-mohamed-ali-ahmed", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-051", title: "ربيع شاعر", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mustafa-abdelrahman", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-052", title: "روحي.. حياتي (الحب بيسأل)", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: "f-fata-ahlami", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-053", title: "ريح دمعك", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: null, filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-054", title: "سلامات ازيكم", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-055", title: "سمراء", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-abdullah-el-faisal", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-056", title: "شغلوني", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-ayyam-wa-layali", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-057", title: "صافيني مرة", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-058", title: "صحبة الورد", year: null, decade: 1950, composerId: "c-fouad-helmi", lyricistId: "l-ahmed-el-samra", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-059", title: "صدفة", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-mawad-gharam", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-060", title: "ظالم", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-061", title: "ظلموه", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-banat-el-yom", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-062", title: "عشانك يا قمر", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mamoun-shinawi", filmId: "f-ayyam-wa-layali", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-063", title: "عقبالك يوم ميلادك", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-banat-el-yom", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-064", title: "على قد الشوق", year: 1955, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mohamed-ali-ahmed", filmId: "f-lahn-el-wafaa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar", "billboard-arabia"] },
    { id: "s-065", title: "العهد الجديد", year: 1952, decade: 1950, composerId: "c-abdelhamid-zaki", lyricistId: "l-mahmoud-abdelhay", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أول نشيد وطني غناه عبدالحليم بعد ثورة 23 يوليو. اشتركت معه عصمت عبد العليم", sources: ["wikipedia-ar", "marefa"] },
    { id: "s-066", title: "العيون بتناجيك", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-067", title: "غني.. غني", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-068", title: "غني يا قلبي", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عند الوحدة مع سوريا", sources: ["wikipedia-ar"] },
    { id: "s-069", title: "فات الربيع", year: null, decade: 1950, composerId: "c-ahmed-sabri", lyricistId: "l-mohamed-ali-ahmed", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-070", title: "فاتوني", year: null, decade: 1950, composerId: "c-riyad-sunbati", lyricistId: "l-saleh-joudat", filmId: "f-layali-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-071", title: "فرحتنا يا هنانا", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-mohamed-halawa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-072", title: "فوق الشوك", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-ali-mahdi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-073", title: "في سكون الليل", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-074", title: "في يوم في شهر في سنة", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-hekayet-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-075", title: "في يوم من الأيام", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-el-wisada-el-khaliya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-076", title: "القرنفل", year: null, decade: 1950, composerId: "c-ali-farag", lyricistId: "l-youssef-izzedin", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-077", title: "قولوله الحقيقة", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-share3-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-078", title: "كان فيه زمان", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-hussein-el-sayed", filmId: "f-dalila", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-079", title: "كفاية نورك", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-layali-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-080", title: "كنت فين", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-banat-el-yom", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-081", title: "لا تلمني", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mohamed-ali-ahmed", filmId: "f-lahn-el-wafaa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-082", title: "لايق عليك الخال", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-abdelmoneim-el-sabaa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-083", title: "لحن الوفاء", year: null, decade: 1950, composerId: "c-riyad-sunbati", lyricistId: "l-mohamed-ali-ahmed", filmId: "f-lahn-el-wafaa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع شادية", sources: ["wikipedia-ar"] },
    { id: "s-084", title: "لقاء", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-abdul-sabour", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "أول أغنية خاصة يسجلها عبدالحليم للإذاعة", sources: ["wikipedia-ar", "marefa"] },
    { id: "s-085", title: "الله يا بلادنا الله", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-anwar-abdullah", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-086", title: "لو كنت يوم أنساك", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mamoun-shinawi", filmId: "f-mawad-gharam", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-087", title: "لو كنت يوم على قلبي تهون", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-el-halwani", filmId: null, categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناها بصوته فقط في فيلم فجر", sources: ["wikipedia-ar"] },
    { id: "s-088", title: "الليالي", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: "f-share3-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-089", title: "اللي انشغلت عليه", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-hussein-el-sayed", filmId: "f-dalila", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-090", title: "الليل أنوار وسمر", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-halawa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-091", title: "ليه تحسب الأيام", year: null, decade: 1950, composerId: "c-ali-farag", lyricistId: "l-fathi-qora", filmId: null, categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناها بصوته فقط في فيلم بعد الوداع", sources: ["wikipedia-ar"] },
    { id: "s-092", title: "ليه تشغل بالك", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: "f-ayyamna-el-helwa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-093", title: "مالك ومالي يا أبو قلب خالي", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-094", title: "متصدقنيش", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-ibrahim-kamel-refaat", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-095", title: "مشغول", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-ismail-el-habrouk", filmId: "f-el-wisada-el-khaliya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-096", title: "مركب الأحلام", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-097", title: "مركب العشاق", year: null, decade: 1950, composerId: "c-abdelhalim-nweira", lyricistId: "l-abdel-fattah-asal", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-098", title: "موالي.. موالي", year: null, decade: 1950, composerId: null, lyricistId: "l-mursi-gamil-aziz", filmId: "f-share3-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-099", title: "نداء الماضي", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mahmoud-hassan-ismail", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-100", title: "نسيم الفجرية", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-hassan-mohamed-haha", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-101", title: "نعم يا حبيبي نعم", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-share3-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-102", title: "هنا روض غرامنا", year: null, decade: 1950, composerId: "c-ahmed-sabri", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-103", title: "هيّ دي هيّ", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-ayyamna-el-helwa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-104", title: "وفاء", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-halawa", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-105", title: "يا إله الكون", year: null, decade: 1950, composerId: "c-hussein-geneid", lyricistId: "l-mustafa-abdelrahman", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-106", title: "يا جمال يا حبيب الملايين", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-ismail-el-habrouk", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-107", title: "يا حلو يا اسمر", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-108", title: "يا سيدي أمرك", year: null, decade: 1950, composerId: "c-mahmoud-el-sharif", lyricistId: "l-fathi-qora", filmId: "f-layali-el-hob", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-109", title: "يا قلبي خبّي", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: "f-ayyamna-el-helwa", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-110", title: "يا قلبي يا خالي", year: null, decade: 1950, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-banat-el-yom", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-111", title: "يا اللي إنتِ نجوى خيالي", year: null, decade: 1950, composerId: "c-abdelhamid-zaki", lyricistId: "l-ibrahim-mohamed-naja", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-112", title: "يا مغرمين", year: null, decade: 1950, composerId: "c-ali-ismail", lyricistId: "l-imam-el-saftawi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-113", title: "يا مواعدني بكرة", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-114", title: "يا ناكر المعروف", year: null, decade: 1950, composerId: "c-ahmed-sabri", lyricistId: "l-ibrahim-rajab", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-115", title: "يللا يا جن", year: null, decade: 1950, composerId: "c-abdelhalim-ali", lyricistId: "l-ibrahim-rajab", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "من برنامج معروف الإسكافي", sources: ["wikipedia-ar"] },
    { id: "s-116", title: "يوم وارتاح", year: null, decade: 1950, composerId: "c-kamal-el-tawil", lyricistId: "l-mohamed-ali-ahmed", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-117", title: "بتقوللي إيه خلاني أحبك", year: null, decade: 1950, composerId: "c-hussein-geneid", lyricistId: "l-ahmed-helmi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-118", title: "بتقوللي بكرة", year: null, decade: 1950, composerId: "c-mohamed-mougi", lyricistId: "l-samir-mahjoub", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },

    // ---- الستينيات 1960-1969 ----
    { id: "s-201", title: "ابنك يقولك يا بطل", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar"] },
    { id: "s-202", title: "أحبك", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: "f-maboudat-el-gamahir", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-203", title: "أحضان الحبايب", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdelrahman-el-abinoudi", filmId: "f-abi-fawq-el-shagara", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-204", title: "احلف بسماها وبترابها", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar", "billboard-arabia"] },
    { id: "s-205", title: "أدعوك يا سامع دعايا", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "ابتهال ديني", sources: ["wikipedia-ar"] },
    { id: "s-206", title: "أدهم الشرقاوي", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناها بصوته فقط في فيلم أدهم الشرقاوي", sources: ["wikipedia-ar"] },
    { id: "s-207", title: "اضرب.. اضرب", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar"] },
    { id: "s-208", title: "اعز الناس", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-209", title: "أنا من تراب", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-210", title: "انذار", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar"] },
    { id: "s-211", title: "بالأحضان", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-212", title: "بالدم", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar"] },
    { id: "s-213", title: "بأمر الحب", year: null, decade: 1960, composerId: "c-mounir-murad", lyricistId: "l-mursi-gamil-aziz", filmId: "f-yawm-min-omri", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-214", title: "بركان الغضب", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar"] },
    { id: "s-215", title: "بستان الاشتراكية", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-216", title: "بعد ايه", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mamoun-shinawi", filmId: "f-yawm-min-omri", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-217", title: "بلاش عتاب", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-maboudat-el-gamahir", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-218", title: "بلدي يا بلدي", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-219", title: "البندقية اتكلمت", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mohsen-el-khayat", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-220", title: "بيني وبين الناس", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-221", title: "أنا كل ما أقول التوبة", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "توزيع علي إسماعيل", sources: ["wikipedia-ar"] },
    { id: "s-222", title: "الثأر", year: null, decade: 1960, composerId: "c-ali-ismail", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "نشيد مع مجموعة مطربين", sources: ["wikipedia-ar"] },
    { id: "s-223", title: "جانا الهوى", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: "f-abi-fawq-el-shagara", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-224", title: "جبار", year: 1967, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-hussein-el-sayed", filmId: "f-maboudat-el-gamahir", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar", "billboard-arabia"] },
    { id: "s-225", title: "الجزائر (قضبان حديد انكسرت)", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-kamel-mansour", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-226", title: "جواب", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-el-banat-wel-sayf", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-227", title: "الجيل الصاعد", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "نشيد مع مجموعة مطربين", sources: ["wikipedia-ar"] },
    { id: "s-228", title: "حاجة غريبة", year: null, decade: 1960, composerId: "c-mounir-murad", lyricistId: "l-hussein-el-sayed", filmId: "f-maboudat-el-gamahir", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "مع شادية", sources: ["wikipedia-ar"] },
    { id: "s-229", title: "حبيبها", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-kamel-el-shinawi", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-230", title: "حكاية شعب", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-231", title: "الحلوة", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-el-khataya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-232", title: "خايف مرة احب", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mamoun-shinawi", filmId: "f-yawm-min-omri", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-233", title: "خليني كلمة", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-234", title: "ذكريات", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-235", title: "راح.. راح", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mursi-gamil-aziz", filmId: "f-el-banat-wel-sayf", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-236", title: "راية العرب", year: 1967, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أثناء حرب 1967", sources: ["wikipedia-ar"] },
    { id: "s-237", title: "صوت الجماهير", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "نشيد مع مجموعة مطربين", sources: ["wikipedia-ar"] },
    { id: "s-238", title: "صورة صورة", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-239", title: "ضحك ولعب وجد وحب", year: null, decade: 1960, composerId: "c-mounir-murad", lyricistId: "l-mursi-gamil-aziz", filmId: "f-yawm-min-omri", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-240", title: "ضي القناديل", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-rahbani-brothers", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-241", title: "سواح", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-242", title: "طاير على جناح الحمام", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-salman", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن لبنان", sources: ["wikipedia-ar"] },
    { id: "s-243", title: "ع التوته", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-244", title: "عدى النهار", year: 1967, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناها في حفلة ألبرت هول", sources: ["wikipedia-ar", "marefa"] },
    { id: "s-245", title: "على حسب وداد قلبي", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-salah-abu-salem", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-246", title: "عيني ضناها السهر", year: null, decade: 1960, composerId: "c-saud-el-rashid", lyricistId: "l-abdulmohsen-el-refai", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-247", title: "فدائي", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-248", title: "الفرح", year: null, decade: 1960, composerId: "c-mounir-murad", lyricistId: "l-hussein-el-sayed", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "ظهرت بعد وفاة عبدالحليم", sources: ["wikipedia-ar"] },
    { id: "s-249", title: "الفنارة", year: null, decade: 1960, composerId: "c-abdelazim-mohamed", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-250", title: "الفوازير", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-251", title: "قاضي البلاج", year: null, decade: 1960, composerId: "c-mounir-murad", lyricistId: "l-mursi-gamil-aziz", filmId: "f-abi-fawq-el-shagara", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-252", title: "قوللي حاجة", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: "f-el-khataya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-253", title: "كامل الأوصاف", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-magdy-naguib", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-254", title: "لست قلبي (أنت قلبي)", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-kamel-el-shinawi", filmId: "f-maboudat-el-gamahir", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-255", title: "ليالي العيد (العيد العيد)", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mohsen-el-khayat", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن الكويت", sources: ["wikipedia-ar"] },
    { id: "s-256", title: "من الجهرة للسلمية", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن الكويت", sources: ["wikipedia-ar"] },
    { id: "s-257", title: "المسؤولية", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-258", title: "أغنية المسيح", year: 1967, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناها في حفلة ألبرت هول بلندن", sources: ["wikipedia-ar", "marefa"] },
    { id: "s-259", title: "مطالب شعب", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-260", title: "مغرور", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-halawa", filmId: "f-el-khataya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-261", title: "من زمان الحرية", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-mamoun-shinawi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-262", title: "ناصر يا حرية", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-263", title: "نفضت عينيا المنام", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-264", title: "الهوى هوايا", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-abdelrahman-el-abinoudi", filmId: "f-abi-fawq-el-shagara", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-265", title: "والحبة في الأرض", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-266", title: "ورحمتك في النسيم", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-267", title: "وحياة قلبي وأفراحه", year: null, decade: 1960, composerId: "c-mounir-murad", lyricistId: "l-fathi-qora", filmId: "f-el-khataya", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-268", title: "ورق الشجر", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-269", title: "الوطن الأكبر", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "نشيد مع مجموعة مطربين", sources: ["wikipedia-ar"] },
    { id: "s-270", title: "الويل الويل", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-saleh-joudat", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-271", title: "يا أهلا بالمعارك", year: 1965, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar", "billboard-arabia"] },
    { id: "s-272", title: "يا بلدنا لا تنامي", year: null, decade: 1960, composerId: "c-ibrahim-rajab", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-273", title: "يا حبايب بالسلامة", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-274", title: "يا خالق الزهرة", year: null, decade: 1960, composerId: "c-mohamed-mougi", lyricistId: "l-abdel-fattah-mustafa", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناء ديني", sources: ["wikipedia-ar"] },
    { id: "s-275", title: "يا خلى القلب", year: null, decade: 1960, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mursi-gamil-aziz", filmId: "f-abi-fawq-el-shagara", categoryId: "cat-film", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-276", title: "يا فرحة السمار", year: null, decade: 1960, composerId: "c-hamad-el-rajib", lyricistId: "l-ahmed-el-adwani", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-277", title: "يا مولعين بالسهر", year: null, decade: 1960, composerId: "c-balegh-hamdi", lyricistId: "l-abdelmajid-bin-jeddo", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن تونس", sources: ["wikipedia-ar"] },
    { id: "s-278", title: "يا هلى يا هلى", year: null, decade: 1960, composerId: "c-abdelhamid-el-sayed", lyricistId: "l-walid-jaafar", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar"] },
    { id: "s-279", title: "صورة", year: 1966, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-salah-jahin", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-ar", "billboard-arabia"] },
    { id: "s-280", title: "خدني معاك يا هوا", year: null, decade: 1960, composerId: "c-kamal-el-tawil", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن الكويت", sources: ["wikipedia-ar"] },

    // ---- السبعينيات 1970-1977 ----
    { id: "s-301", title: "استعراض الطلبة", year: null, decade: 1970, composerId: "c-mounir-murad", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "مع عادل إمام في المسلسل الإذاعي أرجوك لا تفهمني بسرعة", sources: ["wikipedia-arz"] },
    { id: "s-302", title: "اطلب يا شباب", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-303", title: "آه يا ليلة جميلة محلاكي", year: null, decade: 1970, composerId: null, lyricistId: null, filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن المغرب", sources: ["wikipedia-arz"] },
    { id: "s-304", title: "أي دمعة حزن لا", year: 1974, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-305", title: "باحلم بيوم", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "مسلسل أرجوك لا تفهمني بسرعة", sources: ["wikipedia-arz"] },
    { id: "s-306", title: "حاول تفتكرني", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-307", title: "حبيبتي من تكون", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-khaled-bin-saud", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "نُشرت بعد وفاة عبدالحليم", sources: ["wikipedia-arz"] },
    { id: "s-308", title: "خلي السلاح صاحي", year: null, decade: 1970, composerId: "c-kamal-el-tawil", lyricistId: "l-ahmed-shafik-kamel", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-309", title: "رسالة من تحت الماء", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-nizar-qabbani", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-310", title: "زي الهوا", year: 1970, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-311", title: "صباح الخير يا سينا", year: null, decade: 1970, composerId: "c-kamal-el-tawil", lyricistId: "l-abdelrahman-el-abinoudi", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-312", title: "عاش اللي قال", year: 1973, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "أول أغنية غناها بعد نصر أكتوبر 1973", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-313", title: "عيد ميلاد الحسن", year: null, decade: 1970, composerId: "c-helmi-bakr", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن المغرب", sources: ["wikipedia-arz"] },
    { id: "s-314", title: "فاتت جنبنا", year: 1974, decade: 1970, composerId: "c-mohamed-abdelwahab", lyricistId: "l-hussein-el-sayed", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-315", title: "الفجر لاح", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-316", title: "فيه ناس", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-317", title: "قارئة الفنجان", year: 1976, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-nizar-qabbani", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "آخر ما غنى عبدالحليم حافظ", sources: ["wikipedia-arz", "marefa", "billboard-arabia"] },
    { id: "s-318", title: "قومي يا مصر", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-abdelrahim-mansour", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-319", title: "لفي البلاد يا صبية", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohsen-el-khayat", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-320", title: "ليالي العيد", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن المغرب", sources: ["wikipedia-arz"] },
    { id: "s-321", title: "ليلة القمر", year: null, decade: 1970, composerId: "c-helmi-bakr", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن المغرب", sources: ["wikipedia-arz"] },
    { id: "s-322", title: "الماية والخضرة", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن المغرب", sources: ["wikipedia-arz"] },
    { id: "s-323", title: "ماشي الطريق", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-radio", recordingType: "إذاعي", concertId: null, audioUrl: "", notes: "مسلسل أرجوك لا تفهمني بسرعة", sources: ["wikipedia-arz"] },
    { id: "s-324", title: "مداح القمر", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-325", title: "المركبة عدت", year: null, decade: 1970, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mustafa-el-damrani", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-326", title: "مصر", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-abdelrahim-mansour", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-327", title: "موعود", year: null, decade: 1970, composerId: "c-balegh-hamdi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-328", title: "مين أنا", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-329", title: "ناداني الحب", year: null, decade: 1970, composerId: "c-helmi-bakr", lyricistId: "l-abdelwahab-mohamed", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "عن المغرب", sources: ["wikipedia-arz"] },
    { id: "s-330", title: "نبتدي منين الحكاية", year: null, decade: 1970, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-331", title: "النجمة مالت على القمر", year: 1975, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohsen-el-khayat", filmId: null, categoryId: "cat-national", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "غناها بعد إعادة افتتاح قناة السويس", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-332", title: "ولله ما أقول اللآه", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-religious", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-333", title: "يا مالكًا قلبي", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-abdullah-el-faisal", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-334", title: "يا مركبي سيري", year: null, decade: 1970, composerId: "c-mohamed-mougi", lyricistId: "l-mohamed-hamza", filmId: null, categoryId: "cat-other", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz"] },
    { id: "s-335", title: "لا تكذبي", year: null, decade: 1970, composerId: "c-mohamed-abdelwahab", lyricistId: "l-kamel-el-shinawi", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "", sources: ["wikipedia-arz", "marefa"] },
    { id: "s-336", title: "من غير ليه", year: null, decade: 1970, composerId: "c-mohamed-abdelwahab", lyricistId: "l-mursi-gamil-aziz", filmId: null, categoryId: "cat-romantic", recordingType: "استوديو", concertId: null, audioUrl: "", notes: "بروفة فقط؛ لم يمهله القدر لكي يغنيها", sources: ["marefa"] },
  ],

  /* ===== السيرة الذاتية ===== */
  biography: {
    fullName: "عبد الحليم علي إسماعيل شبانة",
    stageName: "عبد الحليم حافظ",
    birthDate: "21 يونيو 1929",
    birthPlace: "قرية الحلوات، محافظة الشرقية، مصر",
    deathDate: "30 مارس 1977",
    deathPlace: "لندن، إنجلترا",
    titles: ["العندليب الأسمر", "مطرب الثورة"],
    sections: [
      {
        title: "الميلاد والنشأة",
        content: "وُلد عبد الحليم علي إسماعيل شبانة في 21 يونيو 1929 بقرية الحلوات بمحافظة الشرقية في مصر. توفيت والدته في اليوم نفسه الذي وُلد فيه، فنشأ يتيمًا منذ يوم ولادته. توفي والده قبل أن يتم عامه الأول، فعاش بعد ذلك في بيت خاله الحاج متولي عماشة. كان الابن الرابع لأسرته، وكان أكبر إخوته إسماعيل شبانة، الذي كان مطربًا ومدرسًا للموسيقى في وزارة التربية."
      },
      {
        title: "الطفولة والدراسة",
        content: "التحق عبد الحليم بعد أن نضج قليلًا بكتاب الشيخ أحمد. ظهر حبه للموسيقى منذ دخوله المدرسة، فأصبح رئيسًا لفرقة الأناشيد في مدرسته. حاول منذ ذلك الوقت دخول مجال الغناء لشدة ولعه به. التحق بمعهد الموسيقى العربية عام 1943 في قسم التلحين، والتقى فيه بالفنان كمال الطويل، الذي كان في قسم الغناء والأصوات. درسا معًا حتى تخرجهما عام 1949."
      },
      {
        title: "العمل قبل الشهرة",
        content: "رُشح عبد الحليم للسفر في بعثة حكومية إلى الخارج لكنه ألغى سفره. عمل مدرسًا للموسيقى لمدة أربع سنوات في طنطا ثم الزقازيق ثم القاهرة. قدم استقالته من التدريس والتحق بفرقة الإذاعة الموسيقية عازفًا على آلة الأبواه عام 1950. تقابل مع صديق ورفيق عمره مجدي العمروسي عام 1951 في بيت مدير الإذاعة آنذاك، الإذاعي فهمي عمر."
      },
      {
        title: "بداية الغناء والاسم الفني",
        content: "اكتشفه الإذاعي الكبير حافظ عبد الوهاب، الذي سمح له باستخدام اسم «حافظ» بدلًا من «شبانة». عند محاولته الغناء أول مرة، تعرض للانتقاد بسبب أغنية «صافيني مرة» التي لحنها محمد الموجي، وقصيدة «لقاء» لصلاح عبد الصبور. كان أسلوب الأغنيتين مختلفًا، ورفضتهما الجماهير في البداية لأنها لم تكن مستعدة لتلقي هذا النوع الجديد من الغناء. نجح بعد ذلك نجاحًا ساحقًا، حتى لُقب بـ«العندليب الأسمر»."
      },
      {
        title: "التعاونات الفنية",
        content: "تعاون عبد الحليم مع كبار الملحنين والشعراء. شكل مع محمد الموجي وكمال الطويل ثم بليغ حمدي ثنائيًا فنيًا قدم أبرز الأغاني العربية. غنى عددًا من الأغاني الشهيرة من ألحان موسيقار الأجيال محمد عبد الوهاب، منها: «أهواك»، «نبتدي منين الحكاية»، «فاتت جنبنا». شكل مع بليغ حمدي والشاعر محمد حمزة ثلاثيًا قدم عددًا من الأغاني العربية البارزة، ومنها: «زي الهوا»، «سواح»، «حاول تفتكرني»، «أي دمعة حزن لا»، «موعود». غنى للشاعر نزار قباني أغنية «قارئة الفنجان» و«رسالة من تحت الماء»، ولحنهما محمد الموجي."
      },
      {
        title: "السينما",
        content: "قدم عبد الحليم حافظ للسينما 16 فيلمًا سينمائيًا، كان أولها «لحن الوفاء» عام 1955 الذي شاركته البطولة شادية، وآخرها «أبي فوق الشجرة» عام 1969. شارك في بطولة أفلامه كبار نجوم السينما المصرية مثل فاتن حمامة وعمر الشريف وأحمد رمزي وشادية."
      },
      {
        title: "الحفلات",
        content: "أقام عبد الحليم حافظ حفلاتٍ تاريخية عديدة. بعد حرب 1967، غنى في حفلة تاريخية أمام 8 آلاف شخص في قاعة ألبرت هول بلندن لصالح المجهود الحربي، وقدم فيها أغنية «المسيح» و«عدى النهار». في أكتوبر 1974، غنى في باريس أمام حوالي 7000 مشاهد. كان صديقًا للزعيم الحبيب بورقيبة، والحسن الثاني، والملك حسين."
      },
      {
        title: "الغناء الوطني",
        content: "كان عبد الحليم يُسمى «مطرب الثورة»، وكان ممثلًا لمبادئ ثورة 23 يوليو والحلم المصري في أغانيه الوطنية. قيل إن أغاني عبد الحليم حافظ كانت «ثورة 23 يوليو على شكل أغانٍ وألحان». غنى أغنيات وطنية مهمة مثل «إحنا الشعب»، «يا جمال يا حبيب الملايين»، «صباح الخير يا سينا»، «ابنك يقولك يا بطل»، «حكاية شعب»، «الوطن الأكبر»."
      },
      {
        title: "المرض والوفاة",
        content: "أصيب عبد الحليم بتليف في الكبد بسبب داء البلهارسيات. كانت أول مرة عرف فيها بمرضه عام 1956، حين أصيب بأول نزيف في المعدة. ظل يصارع المرض لسنوات، وتلقى العلاج على يد عدد من الأطباء في مصر وخارجها. توفي يوم الأربعاء 30 مارس 1977 في لندن أثناء رحلة علاجه، عن عمر يناهز نحو 48 عامًا."
      },
      {
        title: "الإرث الفني",
        content: "قدم عبد الحليم حافظ أكثر من 230 أغنية و16 فيلمًا سينمائيًا. جمع مجدي العمروسي غالبية أغانيه في كتاب بعنوان «كراسة الحب والوطنية... السجل الكامل لكل ما غناه العندليب الأسمر عبد الحليم حافظ». كما أصدر الباحث عمرو فتحي موسوعة مفصلة تضم أكثر من 300 أغنية قدمها عبد الحليم خلال مسيرته. لا تزال أغانيه تتصدر قوائم الأكثر استماعًا حتى اليوم، ويُعد أحد أبرز رموز الغناء العربي في القرن العشرين."
      }
    ]
  },

  /* ===== المصادر ===== */
  sources: [
    { id: "wikipedia-ar", name: "ويكيبيديا العربية — قائمة أغاني عبد الحليم حافظ", url: "https://ar.wikipedia.org/wiki/قائمة_أغاني_عبد_الحليم_حافظ" },
    { id: "wikipedia-ar-bio", name: "ويكيبيديا العربية — عبد الحليم حافظ", url: "https://ar.wikipedia.org/wiki/عبد_الحليم_حافظ" },
    { id: "wikipedia-arz", name: "ويكيبيديا المصرية — ليستة اغانى عبد الحليم حافظ", url: "https://arz.wikipedia.org/wiki/ليستة_اغانى_عبد_الحليم_حافظ" },
    { id: "marefa", name: "موسوعة المعرفة — عبد الحليم حافظ", url: "https://www.marefa.org/عبد_الحليم_حافظ" },
    { id: "billboard-arabia", name: "بيلبورد العربية — عبد الحليم حافظ", url: "https://www.billboardarabia.com/artist-details/عبد-الحليم-حافظ" },
    { id: "sis-gov", name: "الهيئة العامة للاستعلامات — عبد الحليم حافظ", url: "https://sis.gov.eg/ar/مصر/أعلام-وشخصيات-مصرية/عبد-الحليم-حافظ-1/" },
    { id: "aljazeera", name: "الجزيرة — موسوعة: عبد الحليم حافظ", url: "https://www.aljazeera.net/encyclopedia/2015/3/14/عبد-الحليم-حافظ" },
    { id: "elcinema", name: "السينما.كوم — عبدالحليم حافظ", url: "https://elcinema.com/person/1092937/" },
    { id: "langue-arabe", name: "موسوعة أغاني عبد الحليم حافظ — عمرو فتحي", url: "https://langue-arabe.ac-versailles.fr/موسوعة-أغاني-عبد-الحليم-حافظ-للباحث-المصري-عمرو-فتحي" },
  ],

  /* ===== الصور (placeholder — تضاف لاحقًا) ===== */
  photos: [
    { id: "photo-001", title: "صورة شخصية لعبدالحليم حافظ", year: null, category: "صور شخصية", description: "", source: "", rights: "Rights status unknown", url: "" },
    { id: "photo-002", title: "صورة من حفلة", year: null, category: "صور الحفلات", description: "", source: "", rights: "Rights status unknown", url: "" },
    { id: "photo-003", title: "صورة من فيلم", year: null, category: "صور الأفلام", description: "", source: "", rights: "Rights status unknown", url: "" },
  ],
};

// جعل البيانات متاحة عالميًا
if (typeof window !== 'undefined') {
  window.ARCHIVE_DATA = ARCHIVE_DATA;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ARCHIVE_DATA;
}
